name: projetoativa
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48144
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fdaf17'
    - '#ec155b'
    - '#01aef0'
    - '#f57aa4'
  brandStrength: 0.5834997994825244
  lightness: 0.5425193167757243
  saturation: 0.6336082250345498
  rhythmicContrast: 0.0646549565717578
purpose: []
